---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ template "name" . }}.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "name" . }}
              servicePort: http